// SharpDX.DirectInput/Generated/Enumerations.cs
namespace ynv
{
    public enum KeyCode : int
    {
        None              = -1,  //無し
        Unknown           = 0,   // 不明
        F1                = 59,
        F2                = 60,
        F3                = 61,
        F4                = 62,
        F5                = 63,
        F6                = 64,
        F7                = 65,
        F8                = 66,
        F9                = 67,
        F10               = 68,
        F11               = 87,
        F12               = 88,
        F13               = 100,
        F14               = 101,
        F15               = 102,
        D1                = 2,   // 1
        D2                = 3,   // 2
        D3                = 4,   // 3
        D4                = 5,   // 4
        D5                = 6,   // 5
        D6                = 7,   // 6
        D7                = 8,   // 7
        D8                = 9,   // 8
        D9                = 10,  // 9
        D0                = 11,  // 0
        A                 = 30,
        B                 = 48,
        C                 = 46,
        D                 = 32,
        E                 = 18,
        F                 = 33,
        G                 = 34,
        H                 = 35,
        I                 = 23,
        J                 = 36,
        K                 = 37,
        L                 = 38,
        M                 = 50,
        N                 = 49,
        O                 = 24,
        P                 = 25,
        Q                 = 16,
        R                 = 19,
        S                 = 31,
        T                 = 20,
        U                 = 22,
        V                 = 47,
        W                 = 17,
        X                 = 45,
        Y                 = 21,
        Z                 = 44,
        Escape            = 1,   // ESC
        Tab               = 15,
        Capital           = 58,  // Caps Lock
        Back              = 14,  // BS
        Insert            = 210,
        Delete            = 211, // Del
        Return            = 28,  // Enter
        Apostrophe        = 40,  // '
        Minus             = 12,  // -
        Backslash         = 43,
        Yen               = 125, // \
        AT                = 145, // @
        Semicolon         = 39,  // ;
        Colon             = 146, // :
        LeftBracket       = 26,  // [
        RightBracket      = 27,  // ]
        Comma             = 51,  // ,
        Period            = 52,  // .
        Slash             = 53,  // /
        Underline         = 147, // _
        Up                = 200, // ↑
        Down              = 208, // ↓
        Left              = 203, // ←
        Right             = 205, // →
        Home              = 199,
        End               = 207,
        PageUp            = 201,
        PageDown          = 209,
        PrintScreen       = 183,
        ScrollLock        = 70,
        Pause             = 197,
        NumberLock        = 69,
        Space             = 57,  // 空白
        LeftAlt           = 56,  // 左Alt
        RightAlt          = 184, // 右Alt
        LeftControl       = 29,  // 左Ctrl
        RightControl      = 157, // 右Ctrl
        LeftShift         = 42,  // 左シフト
        RightShift        = 54,  // 右Shift
        LeftWindowsKey    = 219,
        RightWindowsKey   = 220,
        Convert           = 121, // 変換
        NoConvert         = 123, // 無変換
        Kana              = 112, // かなモード
        Kanji             = 148, // 漢字モード
        Applications      = 221, // メニューキー
        NumberPad0        = 82,
        NumberPad1        = 79,
        NumberPad2        = 80,
        NumberPad3        = 81,
        NumberPad4        = 75,
        NumberPad5        = 76,
        NumberPad6        = 77,
        NumberPad7        = 71,
        NumberPad8        = 72,
        NumberPad9        = 73,
        NumberPadComma    = 179, // NumPad ,
        NumberPadEnter    = 156, // NumPad Enter
        NumberPadEquals   = 141, // NumPad =
        Add               = 78,  // NumPad +
        Subtract          = 74,  // NumPad -
        Multiply          = 55,  // NumPad *
        Divide            = 181, // NumPad /
        Decimal           = 83,  // NumPad .
        AX                = 150,
        AbntC1            = 115,
        AbntC2            = 126,
        Calculator        = 161,
        Equals            = 13,
        Grave             = 41,  // `
        Mail              = 236,
        MediaSelect       = 237,
        MediaStop         = 164,
        Mute              = 160,
        MyComputer        = 235,
        NextTrack         = 153,
        Oem102            = 86,
        PlayPause         = 162,
        Power             = 222,
        PreviousTrack     = 144,
        Sleep             = 223,
        Stop              = 149,
        Unlabeled         = 151,
        VolumeDown        = 174,
        VolumeUp          = 176,
        Wake              = 227,
        WebBack           = 234,
        WebFavorites      = 230,
        WebForward        = 233,
        WebHome           = 178,
        WebRefresh        = 231,
        WebSearch         = 229,
        WebStop           = 232,
    }
}
